config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i(show create destroy)
  resources :channels, only: %i(index show)
  resources :messages, only: %i(create)

  root 'main#index'
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/models/channel.rb
class Channel
  include ActiveModel::Model

  CHANNEL_NAMES = %w(sales developers designers).freeze

  attr_accessor :id
  alias_attribute :name, :id

  def self.all
    CHANNEL_NAMES.map { |channel_name| new id: channel_name }
  end

  def to_param
    id
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :channel_id, :body

  def save
    return if channel_id.blank? || body.blank?

    broadcast!
  end

  private

  def broadcast!
    ActionCable.server.broadcast "#{channel_id}_channel", message: "you type: #{body}"
  end
end

app/models/session.rb
class Session
  include ActiveModel::Model
  include ActiveModel::Validations

  USERNAMES_PASSWORDS = {
    'emran' => 'emran',
    'zakwan' => 'zakwan'
  }.freeze

  attr_accessor :username, :password
  attr_reader :uuid

  validates_presence_of :username, :password

  validates_each :username, :password do |record, attr, value|
    next if record.errors.messages.key?(attr)
    collection = USERNAMES_PASSWORDS.send(attr == :password ? :values : :keys)
    record.errors.add attr, 'is incorrect' if collection.exclude? value
  end

  def initialize(attributes = {})
    super
    @uuid = Base64.urlsafe_encode64(username) if username
  end

  def self.find(uuid)
    return if uuid.blank?

    username = Base64.urlsafe_decode64(uuid)
    return if USERNAMES_PASSWORDS.keys.exclude? username

    new username: username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticated?

  def authenticated?
    @current_user = Session.find(cookies.signed[:uuid])
    return true if @current_user

    redirect_to root_url
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
  end

  def show
    @channel = Channel.new id: params[:id]
    @message = Message.new channel_id: @channel.id
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticated?

  def index
    redirect_to channels_path if Session.find(cookies.signed[:uuid])

    @session = Session.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticated?, except: :destroy

  def show
    redirect_to root_path
  end

  # POST /session
  def create
    @session = Session.new(session_params)

    respond_to do |format|
      if @session.valid?
        cookies.signed[:uuid] = @session.uuid
        format.html { redirect_to channels_url, notice: 'Session was successfully created.' }
        format.json { render :show, status: :created, location: @session }
      else
        format.html { render :new }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /session
  def destroy
    cookies.signed[:uuid] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/channels/index.html.erb
<h2>Channels</h2>

<ul>
<% @channels.each do |channel| %>
  <li><%= link_to channel.name.titleize, channel_path(channel) %></li>
<% end %>
</ul>

app/views/channels/show.html.erb
<br>

<h2><%= "#{@channel.name.titleize} Channel" %></h2>
<%= link_to 'Back to Channels', channels_path %>

<br><br>
<%= render 'messages/form', message: @message %>
<br>

<h3>Messages</h3>

<div id="messages" data-channel-id="<%= @channel.name %>">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatSystem</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Chat System</h1>

    <% if @current_user %>
      <p>
        Hello <%= @current_user.username %>
        (<%= link_to 'Logout', session_path, method: :delete %>)!
      </p>
    <% end %>

    <p id="notice"><%= notice %></p>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= render 'sessions/form', session: @session %>

app/views/messages/_form.html.erb
<%= form_with(model: message, remote: true, id: :message_form) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :channel_id, id: :channel_id %>

  <div class="field">
    <%= form.label :body, 'Type your message:' %><br>
    <%= form.text_area :body, id: :message_body, size: '50x10' %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Post Message" %>
  </div>
<% end %>